[PHP]
; Maximize speed, minimize footprint
memory_limit = 128M
max_execution_time = 60
upload_max_filesize = 64M
post_max_size = 64M
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
log_errors = On

; Optimización de OPcache (Crucial para velocidad)
[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=64
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.revalidate_freq=0
opcache.validate_timestamps=0 ; En producción no chequeamos cambios de archivos
opcache.save_comments=1

; JIT (Solo si querés velocidad extra, usa un poco más de RAM)
; opcache.jit=tracing
; opcache.jit_buffer_size=16M
